name = "AudioReader"
uuid = "a9c2ce0f-e965-4f6d-9ec4-ce2d5ed55f28"
authors = ["Riccardo PASINI"]
version = "1.0.0-DEV"

[deps]
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FixedPointNumbers = "0.8.5"
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
